config/routes.rb
Rails.application.routes.draw do




  devise_for :members, :controllers => {
   :registrations => 'members/registrations',
   :sessions => 'members/sessions'
  }

  root to: 'members/homes#top'

  devise_for :admins, :controllers => {
   :registrations => 'admins/registrations',
   :sessions => 'admins/sessions'
  }

  get '/about' => 'members/homes#about'
  get '/admins' => 'admin/homes#top'
  post 'orders/confirm' => 'members/orders#confirm'
  get 'orders/complete' => 'members/orders#complete'
  

  namespace :admins do
    resources :items
    resources :members
    resources :addresses
    resources :admins
    resources :categories
    resources :items
    resources :orders
  end

  namespace :members do
    resources :items
    resources :members
      get 'members/:id/quit' => 'unsubscribe#quit', as: 'quit_members'
      patch 'members/out/:id' => 'unsubscribe#out', as: 'out_member'
    resources :addresses,only: [:new, :create, :index, :edit, :update, :destroy]
    resources :cart_items,only: [:create, :index, :update, :destroy] do
      collection do
        delete '/' => 'cart_items#destroy_all'
      end
    end
    resources :categories
    resources :ordered_items
      get "orders/confirm" => "orders#confirm"
      post "orders/confirm" => "orders#confirm"
      get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :show, :create, :new]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :orders, dependent: :destroy

  has_many :addresses, dependent: :destroy

  has_many :cart_items, dependent: :destroy


  def active_for_authentication?
    super && (self.status == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member
  has_many :ordered_items, dependent: :destroy
  #validates :addresses, presence: true
  
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

end

app/controllers/admins/members_controller.rb
class Admins::MembersController < ApplicationController
  def index
    @members = Member.all
  end
  
  def show
    @member = Member.find(params[:id])
  end
  
  def edit
    @member = Member.find(params[:id])
  end
  
  def update
    @member = Member.find(params[:id])
      if @member.update(member_params)
        redirect_to admins_member_path(@member.id)
      else
        render :edit
      end
  end
  
  private

  def member_params
    params.require(:member).permit(:lastname, :firstname, :lastruby, :firstruby, :zip, :address, :tel, :email, :status)
  end
end

app/controllers/admins/orders_controller.rb
class Admins::OrdersController < ApplicationController

  def index
  end

end

app/controllers/members/addresses_controller.rb
class Members::AddressesController < ApplicationController

   before_action :authenticate_member!

  def index
      @addresses = current_member.addresses
      @address = Address.new
  end


  def create
      @address = Address.new(address_params)
      @address.member_id = current_member.id
      @addresses = current_member.addresses
       if @address.save
          flash[:notice] = "新規配送先を登録しました"
          redirect_to "/members/addresses"
       else
          @addresses = current_member.address
          flash[:notice] = "登録に失敗しました。もう１度入力をお願いします"
          redirect_to "/members/addresses"
       end
  end

  def edit
      @address = Address.find(params[:id])
  end

  def update
      @address = Address.find(params[:id])
    if @address.update(address_params)
        flash[:notice] = "配送先を変更しました"
        redirect_to "/members/addresses"
    else
        render "edit"
    end
  end

  def destroy
      @address = Address.find(params[:id])
      @address.destroy
      @addresses = current_member.address
      flash[:notice] = "配送先を削除しました"
      redirect_to "/members/addresses"
  end

  private

 def address_params
   params.require(:address).permit(:zip, :address, :name)
 end

end

app/controllers/members/cart_items_controller.rb
class Members::CartItemsController < ApplicationController

  def index
    @cart_items = current_member.cart_items
    @sum = 0
  end

  def create
    @cart_item = current_member.cart_items.new(cart_item_params)
    @cart_items = current_member.cart_items
      if @cart_items.find_by(item_id: params[:cart_item][:item_id]).present?
        cart_item = @cart_items.find_by(item_id: params[:cart_item][:item_id])
        cart_item.piece += params[:cart_item][:piece].to_i
        cart_item.save
        @cart_item.delete
      end
    @cart_item.save
    redirect_to members_cart_items_path
  end

  def update
    @cart_items = current_member.cart_items
    @cart_item = @cart_items.find(params[:id])
    @cart_item.update(piece: params[:piece].to_i)
    redirect_to '/members/cart_items'
  end

  def destroy
    @cart_items = current_member.cart_items
    @cart_item = @cart_items.find(params[:id])
    @cart_item.destroy
    flash[:notice] = 'カート内の商品が削除されました'
    redirect_to '/members/cart_items'
  end

  def destroy_all
    @cart_items = current_member.cart_items
    @cart_items.destroy_all
    flash[:notice] = 'カート内が空になりました'
    redirect_to '/members/cart_items'
  end

  private

  def cart_item_params
    params.require(:cart_item).permit(:member_id, :item_id, :piece)
  end
# 参考資料： https://qiita.com/Doppon/items/3947c0027d9ea555cc39 /  https://zenn.dev/akhmgc/articles/2d060378c4260e

end

app/controllers/members/categories_controller.rb
class Members::CategoriesController < ApplicationController
    
end

app/controllers/members/confirmations_controller.rb
# frozen_string_literal: true

class Members::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/members/homes_controller.rb
class Members::HomesController < ApplicationController
  
  def top
    @categories = Category.all
    @items = Item.limit(4)
  end
  
  def about 
  end
  
end

app/controllers/members/items_controller.rb
class Members::ItemsController < ApplicationController

  def index
    @items = Item.paginate(page: params[:page], per_page: 2)
    @categories = Category.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

end

app/controllers/members/members_controller.rb
class Members::MembersController < ApplicationController

  def index
  end

  def edit
    @member = Member.find(params[:id])
      if @member != current_member
         redirect_to edit_members_member_path(@member.id)
      end
  end

  def update
    @member = Member.find(params[:id])
      if @member.update(member_params)
        redirect_to members_member_path(@member.id)
      else
        render :edit
      end
  end

  def show
    @member = current_member
  end


  private

  def member_params
    params.require(:member).permit(:lastname, :firstname, :lastruby, :firstruby, :zip, :address, :tel, :email, :status)
  end

end

app/controllers/members/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Members::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/members/ordered_items_controller.rb
class Members::OrderedItemsController < ApplicationController
end

app/controllers/members/orders_controller.rb
class Members::OrdersController < ApplicationController

  def index
    @orders = current_member.orders.all
    # page(params[:page]).per(6).order(created_at: 'DESC')
  end

  def show
    @order = Order.find(params[:id])
    @order_items = @order.ordered_items
    @tax = 1.08
  end

  def new
    @order = Order.new
    @order.member_id = current_member.id
    @addresses = current_member.addresses
  #  ↑メールアドレスを表記させるのに必要なので
  end

  def confirm
    @cart_items = current_member.cart_items
    @order = Order.new(order_params)
    @order.shipping_fee = 300
    @order.payment_method = params[:order][:payment_method]
    @sum = 0
    @order_amount = 300



    #お届け先
    if params[:order][:address_num] == "0"#登録済みから選択
      @address = Address.find(params[:order][:address_id])
      @order.delivery_zip = @address.zip
      @order.delivery_address = @address.address
      @order.delivery_name = @address.name
    elsif params[:order][:address_num] == "1"#お届け先新規登録
      @order.delivery_zip = params[:order][:delivery_zip]
      @order.delivery_address = params[:order][:delivery_address]
      @order.delivery_name = params[:order][:delivery_name]
    end
  end

  def create
    @cart_items = current_member.cart_items
    @addresses = current_member.addresses
    @order = Order.new(order_params)
    @order.order_status = 0
    @order.member_id = current_member.id
    @order.save

    #商品情報の保存
    cart_items = current_member.cart_items
    cart_items.each do |item|
      ordered_item = OrderedItem.new
      ordered_item.order_id = @order.id
      ordered_item.item_id = item.item.id
      ordered_item.piece = item.piece
      #ordered_item.price_taxin = item.price
      ordered_item.making_status = 0
      ordered_item.save
    end
    current_member.cart_items.destroy_all

    #配送先情報の保存
  unless Member.where(id: @order.member_id).where(zip: @order.delivery_zip).where(address: @order.delivery_address) || Address.where(member_id: @order.member_id).where(name: @order.delivery_name).where(zip: @order.delivery_zip).where(address: order.delivery_address).exits?
    @address = Address.new
    @address.member_id = order.member_id
    @address.name = order.delivery_name
    @address.zip = order.delivery_zip
    @address.address = order.delivery_address
    @address.save
  end
    @cart_items.destroy_all
    redirect_to members_orders_complete_path
  end

  def complete
  end

  private

  def order_params
    params.require(:order)
    .permit(:member_id, :shipping_fee, :order_amount, :payment_method, :delivery_name, :delivery_address, :delivery_zip, :order_status)
    .merge(member_id: current_member.id)
  end
end

















  #def new
    #@order = Order.new
    #@customer = Member.all
  #end

   #def confirm
    #@cart_items = CartItem.where(customer_id: @customer.id)
    # 全ての商品×個数の和に消費税を掛けた値(合計金額)
    #@total_price = (@cart_items.map { |cart_item| cart_item.item.price * cart_item.quantity }.sum * 1.08).floor
    # 現在の住所を使う場合
    #if params[:address] == 'now'
      #@order = Order.new(
        #customer_id: @customer.id,
        #postal_code: @customer.zip,
        #address: @customer.address,
        #name: @customer.lastname + @customer.firstname,
        #payment_way: params[:order][:payment_method]
      #)
    # 配送先登録した住所を使う場合
    #elsif params[:address] == 'select'
      #address =  Address.find_by(id: params[:select]) # params[:select]は選択した住所のid
      #@order = Order.new(
        #customer_id: @customer.id,
        #zip: address.zip,
        #address: address.address,
        #name: address.name,
        #payment_method: params[:order][:payment_method]
      #)
    # 新しく住所を追加する場合
    #elsif params[:address] == 'new'
      #@order = Order.new(order_params)
    #else
      #@order = Order.new(order_params)
    #end
    #if @order.invalid?(:confirm)
      #render :new
    #end
  #end

  #def create
    # カートが空の場合
    #if @customer.cart_items.blank?
      #redirect_to cart_items_path and return
    #end
    #@order = Order.new(order_params)
    #if @order.save
      # 注文商品テーブルのレコードを作成
      #@customer.cart_items.map do |cart_item|
        #OrderItem.create(
          #order_id: @order.id,
          #item_id: cart_item.item_id,
          #quantity: cart_item.quantity,
          #order_status: 'cannot',
          #price: (cart_item.item.price * 1.08).floor
        #)
      #end
      # カートアイテムを空にする
      #@customer.cart_items.destroy_all
      #redirect_to orders_thanks_path
    #else
      #render :new
    #end
  #end
  #def show
    #@order = Order.find(params[:id])
  #end

  #def index
    #@orders = @customer.orders.page(params[:page]).per(6).order(created_at: 'DESC')
  #end

  #private

  #def set_current_customer
    #@customer = current_customer
  #end

app/controllers/members/passwords_controller.rb
# frozen_string_literal: true

class Members::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/members/registrations_controller.rb
# frozen_string_literal: true

class Members::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/sessions_controller.rb
# frozen_string_literal: true

class Members::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
  before_action :reject_member, only: [:create]
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  protected

  def reject_member
    @member = Member.find_by(email: params[:member][:email].downcase)
    if @member
      if (@member.valid_password?(params[:member][:password]) && (@member.active_for_authentication? == false))
        flash[:error] = "退会済みです。"
        redirect_to new_member_session_path
      end
    else
      flash[:error] = "必須項目を入力してください。"
    end
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/members/unlocks_controller.rb
# frozen_string_literal: true

class Members::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/members/unsubscribe_controller.rb
class Members::UnsubscribeController < ApplicationController
  def quit
    @member = current_member
  end

  def out
    @member = current_member
    @member.update(status: true)
    reset_session
    redirect_to root_path
  end
end

app/helpers/admins/members_helper.rb
module Admins::MembersHelper
end

app/views/members/orders/complete.html.erb
 
 
  <section class="py-5 text-center container">
    <div class="row py-lg-5">
      <div class="col-lg-6 col-md-8 mx-auto">
        <h1 class="fw-light">注文完了</h1>
        <p class="lead text-muted">ご注文ありがとうございました。<br>ご注文状況は、注文履歴をご覧ください</p>
        <p>
          <a href="/members/orders" class="btn btn-primary my-2">注文履歴</a>
          <a href="/members/items" class="btn btn-secondary my-2">商品一覧</a>
        </p>
      </div>
    </div>
  </section>

app/views/members/orders/confirm.html.erb
<div class="container">
  <h4>注文情報確認</h4>
    <div class="row">
          <div class="col">
            <% if @cart_items.present? %><!--エラー発生のためコメントアウトしています-->
            <table class="table">
              <thead>
                <tr>
                  <th>商品名</th>
                  <th>単価(税込)</th>
                  <th>数量</th>
                  <th>小計</th>
                </tr>
              </thead>
              <tbody>
                <% @cart_items.each do |cart_item| %>
                  <tr>
                    <td><%= cart_item.item.name  %></td>
                    <td>￥<%= ((cart_item.item.price*1.08).round).to_s(:delimited) %></td>
                    <td><%= cart_item.piece %></td>
                    <td>￥<%= ((cart_item.item.price*1.08)*(cart_item.piece)).round.to_s(:delimited, delimiter: ',') %></td>
                        <% @sum += (cart_item.item.price*1.08)*(cart_item.piece).round %>
                  </tr>
                  <% end %>        
              </tbody>
            </table>
          </div>
          <div class="col">
            <table class="table">
              <tr>
                <th>送料</th>
                <td>￥<%= @order.shipping_fee %></td>
              </tr>
              <tr>
                <th>商品合計</th>
                <td>￥<%= @sum.round.to_s(:delimited) %></td>
              </tr>
              <tr>
                <th>請求金額</th>
                <td>￥<%= ((@order_amount)+(@sum)).round.to_s(:delimited) %></td>
              </tr>
            </table>
          </div>
          <div class="container">
            <h5>支払方法</h5>
              <%= @order.payment_method %><br>
          </div>
          <div class="container">
            <h5>お届け先</h5>
            <span>〒</span>
            <%= @order.delivery_zip %><br>
            <%= @order.delivery_address %><br>
            <%= @order.delivery_name %><br>
          </div>
          <!--上記は実際に表示される記述-->
          <!--下記は確認画面表示のための記述(hidden_fieldのため実際に表示されません)-->
          <div class="container">
            <div class="col-5 confirm_image"></div>
              <div class="col-6">
                <%= form_with model:@order, url: members_orders_path, local:true do |f| %>
                  <%= f.hidden_field :payment_method %>
                  <%= f.hidden_field :delivery_zip %>
                  <%= f.hidden_field :delivery_address %>
                  <%= f.hidden_field :delivery_name %>
                  <%= f.hidden_field :shipping_fee %>
                  <%= f.hidden_field :bill, value: (@sum)+(@order_amount) %>
                  <!--合計金額？-->
                  <%= f.submit "注文確定" %>
              </div>
                <% end %>
  </div>
  <% else %>
  <p>お客様のショッピングカートに商品はありませんので注文確定ができません。</p>
  <p><%= link_to "商品一覧", item_path %>から商品をお探し下さい。</p>
    <% end %>
</div>

app/views/members/orders/index.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-md-8 offset-md-2">

      <h3>注文履歴一覧</h3>
      <table class="mt-5 table table-bordered border-secondary">
        <thead class="table-secondary">
          <tr><th>注文日</th><th>配送先</th><th>注文商品</th><th>支払金額</th><th>ステータス</th><th>注文詳細</th></tr>
        </thead>

        <% @orders.each do |order| %>
        <tbody>
          <tr>
              <td class="align-middle"><%= order.created_at.strftime('%Y/%m/%d') %></td>
              <td><span>〒</span><%= order.delivery_zip %><br><%= order.delivery_address %><br><%= order.delivery_name %></td>
              <td class="align-middle">
                <% order.ordered_items.each do |ordered_item| %>
                  <%= ordered_item.item.name %>
                <% end %>
              </td>
              <td class="align-middle"><%#= order.order_amount.to_s(:delimited) %>円</td>
              <td class="align-middle"><%= order.order_status %></td>
              <td class="align-middle"><%= link_to "表示する", members_order_path(order), class: "btn btn-sm btn-success" %></td>
          </tr>
        <% end %>
      </tbody>

      </table>

app/views/members/orders/new.html.erb
  <body class="bg-light">
    <div class="container">
      <div class="col-md-7 col-lg-8">
        <h2 class="mb-3">注文情報入力</h2>
       <%= form_with(model:@order, url: members_orders_confirm_path, local: true) do |f| %>
               <h3>支払い方法</h3>
                <%= f.radio_button :payment_method, :クレジットカード,  checked: "checked" %>
                <%= f.label :payment_method, "クレジットカード" %><br>
                <%= f.radio_button :payment_method, :銀行振込 %>
                <%= f.label :payment_method, "銀行振込" %>
                
              <div class="mt-2">
                 <h3>お届け先</h3>
                   <%= f.radio_button :address_num,0 %>
                   <%= f.label :address, "登録済み住所選択" %>
                   <div class="ml-3">
                     <%= f.collection_select(:address_id, @addresses, :id, :view_address, {prompt: "選択してください"}, {class: "form-control"}) %>
                   </div>
                   <%= f.radio_button :address_num,1 %>
                   <%= f.label :address, "新しいお届け先" %>
                   <div class="col-sm-6">
                      <%= f.label :"郵便番号(ハイフンなし)" %>
                      <%= f.text_field :delivery_zip, placeholder: "郵便番号", class: "form-control"%>
                   </div>
                   <div class="col-sm-6">
                     <%= f.label :"住所" %>
                     <%= f.text_field :delivery_address, placeholder: "住所", class: "form-control" %>
                   </div>
                   <div class="col-sm-6">
                     <%= f.label :"宛名" %>
                     <%= f.text_field :delivery_name, placeholder: "宛名", class: "form-control" %>
                   </div>
                   <div class="my-3 mr-3">
                     <%= f.submit "注文確認" %>
                   </div>
                  <% end %>
               </div>
         </div>
      </div>
</body>

app/views/members/orders/show.html.erb
<div class="container">
  <div class="row mb-3">
    <h4>注文履歴詳細</h4>
      <div class="row">
      <div class="col-7"><p class="font-weight-bold">注文情報</p></div>
            <div class="col-3"></div>
              <table>
                <tr>
                  <th>注文日</th><th><%= @order.created_at.strftime('%Y/%m/%d') %></th>
                </tr>
                <tr>
                  <th>配送先</th><th><%= @order.delivery_zip %><br><%= @order.delivery_address %><br><%= @order.delivery_name %></th>
                </tr>
                <tr>
                  <th>支払い方法</th><th><%= @order.payment_method %></th>
                </tr>
                <tr><th>ステータス</th><th><%= @order.order_status %></th>
                </tr>
              </table>

            </div>
            <div class="row">注文内容</div>
              <table>
                <tr>
                  <th>商品</th>
                  <th>単価（税込）</th>
                  <th>個数</th>
                  <th>小計</th>
                  <th>配送料</th>
                </tr>
              <% @order_items.each do |ordered_item| %>
                <tr>
                  <th><%= ordered_item.item.name %></th>
                  <th><%= (ordered_item.item.price)*(@tax) %>円</th>
                  <th><%= ordered_item.piece %>個</th>
                  <th><%= (ordered_item.item.price)*(ordered_item.piece) %>円</th>

                </tr>
              <% end %>
            </table>
          </div>
  </div>
</div>