config/routes.rb
Rails.application.routes.draw do




  devise_for :members, :controllers => {
   :registrations => 'members/registrations',
   :sessions => 'members/sessions'
  }

  root to: 'members/homes#top'

  devise_for :admins, :controllers => {
   :registrations => 'admins/registrations',
   :sessions => 'admins/sessions'
  }

  get '/about' => 'members/homes#about'
  get '/admins' => 'admin/homes#top'
  post 'orders/confirm' => 'members/orders#confirm'
  get 'orders/complete' => 'members/orders#complete'
  

  namespace :admins do
    resources :items
    resources :members
    resources :addresses
    resources :admins
    resources :categories
    resources :items
    resources :orders
  end

  namespace :members do
    resources :items
    resources :members
      get 'members/:id/quit' => 'unsubscribe#quit', as: 'quit_members'
      patch 'members/out/:id' => 'unsubscribe#out', as: 'out_member'
    resources :addresses,only: [:new, :create, :index, :edit, :update, :destroy]
    resources :cart_items,only: [:create, :index, :update, :destroy] do
      collection do
        delete '/' => 'cart_items#destroy_all'
      end
    end
    resources :categories
    resources :ordered_items
      get "orders/confirm" => "orders#confirm"
      post "orders/confirm" => "orders#confirm"
      get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :show, :create, :new]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :member
  
  validates :name, :address, presence: true
  validates :zip, length: {is: 7}, numericality: { only_integer: true }
  
  def view_address
    "〒" + self.zip.to_s + "　" + self.address + "　" + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :member
  belongs_to :item
  validates :member_id, :item_id, :piece, presence: true
  validates :piece, numericality: { only_integer: true }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :admins, optional: true
  belongs_to :category
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  attachment :picture
  validates :name, presence: true
  validates :description, presence: true
  validates :price, numericality: { only_integer: true }
  validates :picture, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :orders, dependent: :destroy

  has_many :addresses, dependent: :destroy

  has_many :cart_items, dependent: :destroy


  def active_for_authentication?
    super && (self.status == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member
  has_many :ordered_items, dependent: :destroy
  #validates :addresses, presence: true
  
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admins/items_controller.rb
class Admins::ItemsController < ApplicationController
  
  def index
    @categories = Category.all
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
     redirect_to admins_items_path(@item)
    else
     render :new
    end
  end

  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
      if @item.update(item_params)
        redirect_to admins_item_path(@item)
      else
        render :edit
      end
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    redirect_to admins_items_path
  end

  private

  def item_params
    params.require(:item).permit(:name, :description, :price, :status, :picture, :category_id)#ジャンル未実装
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


before_action :authenticate_any!,except: [:top, :about]



protected

  def authenticate_any!
    if admin_signed_in?
      true
    else
      authenticate_member!
    end
  end



  def after_sign_in_path_for(resource)
    case resource
    when Member
      root_path
    when Admin
      admins_items_path
    end

  end

  def after_sign_out_path_for(resouce)
    root_path
  end

   before_action :configure_permitted_parameters, if: :devise_controller?



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :lastname, :firstname, :lastruby, :firstruby, :zip, :address, :tel])
  end




  # def current_order
  #   Order.find(session[:order_id])
  # rescue ActiveRecord::RecordNotFound
  #   order = Order.create
  #   session[:order_id] = order.id
  #   order
  # end
  #　↑　rails sをしたときにエラーが出るので取り合えず、コメントにしときます。
end

app/controllers/members/items_controller.rb
class Members::ItemsController < ApplicationController

  def index
    @items = Item.paginate(page: params[:page], per_page: 2)
    @categories = Category.all
  end

  def show
    @item = Item.find(params[:id])
    @cart_item = CartItem.new
  end

end

app/helpers/admins/admins_helper.rb
module Admins::AdminsHelper
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins/orders_helper.rb
module Admins::OrdersHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/members/homes_helper.rb
module Members::HomesHelper
end

app/helpers/members/items_helper.rb
module Members::ItemsHelper
end

app/helpers/ordered_items_helper.rb
module OrderedItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/items/edit.html.erb
<div class="container">
   <h3>商品編集</h3>
  <div class="row">

   <%= form_with model: @item, url: admins_items_path, local:true do |f| %>

    <div>
     <%= f.label :picture, "商品画像" %>
     <%= f.attachment_field :picture %>
    </div>

    <div>
     <%= f.label :name, "商品名" %>
     <%= f.text_field :name, placeholder:"商品名" %>
    </div>

    <div>
     <%= f.label :description, "商品説明" %>
     <%= f.text_area :description, placeholder:"ここに説明文を記述します" %>
    </div>

    <div>
     <%= f.collection_select :category_id, Category.all, :id, :category, {prompt: ""}, class: "col-7 p-0" %>

    </div>


    <div>
     <%= f.label :price, "税抜価格" %>
     <%= f.text_field :price %>円
    </div>

    <div>
     <%= f.label :status, "販売ステータス" %>
     <div>
      <%= f.radio_button :status, true %>
      <%= f.label :status, '販売中', value: true %>
     </div>
     <div>
      <%= f.radio_button :status, false %>
      <%= f.label :status, '販売停止中', value: false %>
     </div>
    </div>

    <div>
     <%= f.submit '変更' %>
    </div>
    <div><%= link_to '戻る', admins_item_path(@item) %></div>
   <% end %>
  </div>
</div>

app/views/admins/items/index.html.erb
<div class='container'>
  <div class='row'>
    <h1>商品一覧</h1><div><%= link_to '＋', new_admins_item_path, class: 'btn btn-success' %></div>
    <table class='table table-hover table-inverse'>
      <thead>
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
          <tr>
            <td><%= item.id %></td>
            <td><%= link_to item.name, admins_item_path(item) %></td>
            <td><%= item.price %></td>
            <td>
              <h5><span class="badge rounded-pill bg-primary">カテゴリー</span><h5>
            </td>
            <td>
              <% if item.status? %>
               <h5><span class="badge rounded-pill bg-success">販売中</span></h5>
              <% else %>
               <h5><span class="badge rounded-pill bg-secondary">販売停止中</span></h5>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/admins/items/new.html.erb
<div class="container">
  <div class="row">
   <h3>商品新規登録</h3>

   <%= form_with model: @item, url: admins_items_path, local:true do |f| %>

     <div>
       <%= f.label :picture, "商品画像" %>
       <%= f.attachment_field :picture %>
     </div>

     <div>
       <%= f.label :name, "商品名" %>
       &nbsp;&nbsp;&nbsp; <%= f.text_field :name, placeholder:"商品名" %>
     </div>

     <div>
       <%= f.label :description, "商品説明" %>
       <%= f.text_area :description, placeholder:"ここに説明文を記述します" %>
      </div>

      <div>
        <%= f.label :category_id, "カテゴリー"%>
        <%= f.collection_select :category_id, Category.all, :id, :category %>
      </div>


      <div>
        <%= f.label :price, "税抜価格" %>
        <%= f.text_field :price %>円
      </div>

      <div>
       <%= f.label :status, "販売ステータス" %>
      <div>
        <%= f.radio_button :status, true %>
        <%= f.label :status, '販売中', value: true %>
      </div>
      <div>
        <%= f.radio_button :status, false %>
        <%= f.label :status, '販売停止中', value: false %>
      </div>
    </div>

    <div>
     <%= f.submit '新規登録' %>
    </div>

   <% end %>
  </div>
</div>

app/views/admins/items/show.html.erb
<div class="container">
  <div class='row'>
    <h1>商品詳細</h1>
      <table class='table'>
        <thead>
      	<tr>

  		    <td></td>
          <td>商品名</td>
          <td>商品説明</td>
          <td>税抜価格</td>
          <td colspan="3"></td>

        </tr>
        </thead>
        <tbody>
  		  <tr>
  		    <td><%= attachment_image_tag @item, :picture, :fill, 100, 100, format: 'jpeg' %></td>
          <td><%= @item.name %></td>
          <td><%= @item.description %></td>
          <td><%= @item.price %></td>
          <td>
            <h5><span class="badge rounded-pill bg-primary">カテゴリー</span><h5>
          </td>
          <td>
            <% if @item.status? %>
             <h5><span class="badge rounded-pill bg-success">販売中</span></h5>
            <% else %>
             <h5><span class="badge rounded-pill bg-secondary">販売停止中</span></h5>
            <% end %>
          </td>
          <td><%= link_to 'Edit', edit_admins_item_path, class: "btn btn-sm btn-success" %></td>
          <td><%#= link_to 'Delete', admins_item_path, method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger" %></td>
        </tr>
      </table>
      <h5><%= link_to '戻る', admins_items_path %></h5>
    </div>
  </div>
</div>