config/routes.rb
Rails.application.routes.draw do




  devise_for :members, :controllers => {
   :registrations => 'members/registrations',
   :sessions => 'members/sessions'
  }

  root to: 'members/homes#top'

  devise_for :admins, :controllers => {
   :registrations => 'admins/registrations',
   :sessions => 'admins/sessions'
  }

  get '/about' => 'members/homes#about'
  get '/admins' => 'admin/homes#top'
  post 'orders/confirm' => 'members/orders#confirm'
  get 'orders/complete' => 'members/orders#complete'
  

  namespace :admins do
    resources :items
    resources :members
    resources :addresses
    resources :admins
    resources :categories
    resources :items
    resources :orders
  end

  namespace :members do
    resources :items
    resources :members
      get 'members/:id/quit' => 'unsubscribe#quit', as: 'quit_members'
      patch 'members/out/:id' => 'unsubscribe#out', as: 'out_member'
    resources :addresses,only: [:new, :create, :index, :edit, :update, :destroy]
    resources :cart_items,only: [:create, :index, :update, :destroy] do
      collection do
        delete '/' => 'cart_items#destroy_all'
      end
    end
    resources :categories
    resources :ordered_items
      get "orders/confirm" => "orders#confirm"
      post "orders/confirm" => "orders#confirm"
      get 'orders/complete' => 'orders#complete'
    resources :orders, only: [:index, :show, :create, :new]
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :member
  
  validates :name, :address, presence: true
  validates :zip, length: {is: 7}, numericality: { only_integer: true }
  
  def view_address
    "〒" + self.zip.to_s + "　" + self.address + "　" + self.name
  end

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :items
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :member
  belongs_to :item
  validates :member_id, :item_id, :piece, presence: true
  validates :piece, numericality: { only_integer: true }
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :items, dependent: :destroy
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :admins, optional: true
  belongs_to :category
  has_many :cart_items, dependent: :destroy
  has_many :order_items, dependent: :destroy
  attachment :picture
  validates :name, presence: true
  validates :description, presence: true
  validates :price, numericality: { only_integer: true }
  validates :picture, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  has_many :orders, dependent: :destroy

  has_many :addresses, dependent: :destroy

  has_many :cart_items, dependent: :destroy


  def active_for_authentication?
    super && (self.status == false)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :member
  has_many :ordered_items, dependent: :destroy
  #validates :addresses, presence: true
  
  enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
  enum order_status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4 }

end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :item
  
  enum status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base


before_action :authenticate_any!,except: [:top, :about]



protected

  def authenticate_any!
    if admin_signed_in?
      true
    else
      authenticate_member!
    end
  end



  def after_sign_in_path_for(resource)
    case resource
    when Member
      root_path
    when Admin
      admins_items_path
    end

  end

  def after_sign_out_path_for(resouce)
    root_path
  end

   before_action :configure_permitted_parameters, if: :devise_controller?



  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email, :lastname, :firstname, :lastruby, :firstruby, :zip, :address, :tel])
  end




  # def current_order
  #   Order.find(session[:order_id])
  # rescue ActiveRecord::RecordNotFound
  #   order = Order.create
  #   session[:order_id] = order.id
  #   order
  # end
  #　↑　rails sをしたときにエラーが出るので取り合えず、コメントにしときます。
end

app/helpers/admins/homes_helper.rb
module Admins::HomesHelper
end

app/helpers/admins/items_helper.rb
module Admins::ItemsHelper
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_items_helper.rb
module CartItemsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/ordered_items_helper.rb
module OrderedItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class='container mt-5'>
    <div class='row'>
      <div class='mx-auto'>
        <p>🄫2021 naganocake.</p>
        <% if member_signed_in? %>
        <p>★会員ログイン状態★</p>
        <% end %>
        <% if admin_signed_in? %>
        <p>■管理者ログイン状態■</p>
        <% end %>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
      <%= image_tag 'shortcake.png', class:'short' %>
      <a class="navbar-brand" href="/">Naganocake</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
        <ul class="navbar-nav">

          <% if member_signed_in? %>
          <li class="welcome">ようこそ、<%= current_member.lastname %>さん！&nbsp;&nbsp;</li>
          <li>&nbsp;&nbsp;</li>
          <li>&nbsp;&nbsp;</li>
          <li><%= link_to "Mypage", members_member_path(current_member.id), class: "nav-item nav-link active" %></li>
          <li><%= link_to "About", about_path, class: "nav-item nav-link" %></li>
          <li><%= link_to "Items", members_items_path, class: "nav-item nav-link" %></li>
          <li><%= link_to "Cart items", members_cart_items_path, class: "nav-item nav-link" %></li>
          <li><%= link_to "Logout", destroy_member_session_path, method: :delete, class: "nav-item nav-link" %></li>

          <% elsif admin_signed_in? %>
          <li>&nbsp;&nbsp;</li>
          <li>&nbsp;&nbsp;</li>
          <li>&nbsp;&nbsp;</li>
          <li><%= link_to "Orders", admins_orders_path, class: "nav-item nav-link" %></li>
          <li><%= link_to "Items", '/admins/items', class: "nav-item nav-link" %></li>
          <li><%= link_to "Members", admins_members_path, class: "nav-item nav-link" %></li>
          <li><%= link_to "Categories", admins_categories_path, class: "nav-item nav-link" %></li>
          <li><%= link_to "Logout", destroy_admin_session_path, method: :delete, class: "nav-item nav-link" %></li>

          <% else %>
          <li>&nbsp;&nbsp;</li>
          <li>&nbsp;&nbsp;</li>
          <li>&nbsp;&nbsp;</li>
          <li><%= link_to "About", about_path, class: "nav-item nav-link" %></li>
          <li><%= link_to "Sign_up", new_member_registration_path, class: "nav-item nav-link" %></li>
          <li><%= link_to "Login", new_member_session_path, class: "nav-item nav-link" %></li>
          <li><%= link_to "Admin_login", new_admin_session_path, class: "nav-item nav-link" %></li>
          <% end %>

        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Naganocake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <%= render 'layouts/header' %>

    <main>
       <p id="notice"><%= notice %></p>
       <%= yield %>
       
    </main>

    <%= render 'layouts/footer' %>
  </body>
</html>


<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.css"/>
<link rel="stylesheet" type="text/css" href="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick-theme.css"/>
<script type="text/javascript" src="//cdn.jsdelivr.net/npm/slick-carousel@1.8.1/slick/slick.min.js"></script>